version: "3"

services:
  web:
    container_name: karaokium_web
    env_file: .env.dev
    environment:
      MIX_ENV: ${MIX_ENV:-dev}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/_build
      - /app/deps
      - /app/priv/uploads
      - ${DATABASE_PATH}:/app/priv/repo/databases/
